### ISSUE TITLE
Jobs api gives an error when there are no jobs

### ISSUE THREAD

**Issue by hithwen** [databricks/databricks-cli#172]
# What happens:

## CLI
```
$ databricks  jobs list
Error: KeyError: 'jobs'
```
## SDK
```
>>> jobs_api.list_jobs()
{}
```

# What is expected
## CLI
```
$ databricks  jobs list

```
## SDK
```
>>> jobs_api.list_jobs()
{'jobs': []}
```

**Comment by andrewmchen** [comment]
This is a funny quick with our protobuf serializer. If a repeated is empty then it will not serialize the key at all. Do you want to make a PR? It should be as simple as checking if the API responds without a `jobs` key.

**Comment by hithwen** [comment]
Yeah, but my previous attempt to contribute to this project has been completely ignored: https://github.com/databricks/databricks-cli/pull/169 so I'll pass

**Comment by andrewmchen** [comment]
Sorry about that. I'll take a look at that PR...

**Comment by zhaoxingL** [comment]
@andrewmchen Can this be fixed? I can make a PR towards it. Today when I try to use stack_cli to create a job on a brand new workspace with no jobs, it returns `KeyError` again when checking if there're duplicate jobs using the Jobs API. When I add a `Untitiled` job as placeholder it was successful immediately. Since this is frequently used I think maybe it's worth fixing it.

**Comment by andrewmchen** [comment]
@zhaoxingL Could you try https://github.com/databricks/databricks-cli/pull/230?

**Comment by zhaoxingL** [comment]
@andrewmchen I've tested this and it now can return empty list instead of throwing `KeyError` with existing workspaces. Should be good to merge.
