### ISSUE TITLE
Bad error message when credentials are invalid

### ISSUE THREAD

**Issue by george-unbotify** [databricks/databricks-cli#174]
Used databricks cli to import workspace with bad credentials (invalid Token).
Received the following error message:

```
$ databricks workspace import_dir -o dummy/ /Shared/dummy
Error: ValueError: No JSON object could be decoded
```

**Comment by tiagoh** [comment]
I have exactly the same issue with Databricks CLI version 0.8.2

**Comment by easonlau02** [comment]
Also hit the issue under v0.8.2, but my credentials are absolutely valid. No idea about it.

**Comment by andrewmchen** [comment]
Found a repro for this. It seems that if you include the `o` header in your host this may be a problem. For example, when my profile looks like 
```
[azure]
host = https://westus.azuredatabricks.net/?o=2291051382977284
username = admin
password = admin
```
I will get the `No JSON object could be decoded` error. 

This happens because of how we build the URL, https://github.com/databricks/databricks-cli/blob/master/databricks_cli/sdk/api_client.py#L74. When building it in this way we get a redirect to the login page.

**Comment by easonlau02** [comment]
@andrewmchen Yes. When I remove the URI and keep domain only, it was fixed.
