### ISSUE TITLE
Import_dir importing hidden folders and files

### ISSUE THREAD

**Issue by leonardoheredia** [databricks/databricks-cli#26]
When I use import_dir to import many local files and folders if I have some hidden folder the API importing this folder as well. It is happening with ".git" hidden folder, for example. 
Does it working as expected? Is there a way to avoid import hidden folders and files?

**Comment by andrewmchen** [comment]
Unfortunately, this is the expected behavior of the CLI as it is currently. We may add functionality in the future to be able to ignore certain patterns of files/directories. If you'd like you can take a stab at the feature too :)

For now, can you separate your notebooks directory in an isolated sandbox dir?

**Comment by andrewmchen** [comment]
Closed by https://github.com/databricks/databricks-cli/pull/72.
`databricks workspace import_dir --exclude-hidden-files`
