### ISSUE TITLE
/2.1/jobs/runs/list returning weird number of results

### ISSUE THREAD

**Issue by SqrtPapere** [databricks/databricks-cli#416]
Hi, 

I am using **/2.1/jobs/runs/list** API to retrieve info about all my job runs but the `limit` and `offset` parameters don't seem to be working correctly.

For example, the documentation says that the default value for `limit` is **25** but if I run:

```
tmp_0 = requests.get("https://adb-1234567.16.azuredatabricks.net/api/2.0/jobs/runs/list", headers=headers).json()['runs']
len(tmp_0)  #returns 16! instead of 25
```
The same if I specify a limit:
```
tmp_0 = requests.get("https://adb-123456.16.azuredatabricks.net/api/2.0/jobs/runs/list?limit=25", headers=headers).json()['runs']
len(tmp_0)  #returns 21! instead of 25
```

The same weird result happened with offset:

```
tmp_1 = requests.get("https://adb-123456.16.azuredatabricks.net/api/2.0/jobs/runs/list?offset=0", headers=headers).json()['runs']
len(tmp_1)  #returns 16! instead of 25

tmp_2 = requests.get("https://adb-123456.16.azuredatabricks.net/api/2.0/jobs/runs/list?offset=1", headers=headers).json()['runs']
len(tmp_1)  #returns 17! instead of 25 and the first job_id is overlapping the tmp_1 result, almost as if ignoring offset!
```

Am I doing something wrong?

**Comment by nordp** [comment]
Hello @SqrtPapere!

Are you using the UI as a ground truth reference? You need to make sure there are no changes to the actual runs in your workspace between the calls. Since you're making the two calls one after the other, the correct answer could have changed.

I'm also noticing how you say that you're using API version 2.1, while the calls are made to `api/2.0`.
The pagination behaviour of `runs/list` are different between API 2.1 ([docs](https://docs.databricks.com/dev-tools/api/2.0/jobs.html#runs-list)) and 2.0 ([docs](https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsRunsList))

For the offset, this is in measured in actual rows, so if you want to fetch the "next 25 rows" you should set both limit and offset to "25".

Let me know if anything else is unclear!

**Comment by nfx** [comment]
this issue is not related to CLI
