### ISSUE TITLE
databricks libraries: Can not reinstall/update a library without cluster restart

### ISSUE THREAD

**Issue by theKashyap** [databricks/databricks-cli#548]
* I am developing my project that I build using `poetry`
* I install it on Databricks cluster. Create a wheel based workflow. Run it, find an issue. Fix the issue in code.
* Now if I rebuild the project
  * with same version number and install the wheel file to same cluster OR
  * with different version number and install the wheel file to same cluster OR
  * with same/different version number, uninstall the library from cluster and install the new one

So long as the cluster is not restarted none of these options install the new code on to the cluster. If I restart the cluster it picks up the newest wheel file.

Rebuild and push it to databricks workspace.
```
poetry build
whl_file=$(ls -1tr dist/fxc_dbk-0.1*-py3-none-any.whl | tail -1 | xargs basename)
USER_NAME='kash@abc.com'
echo 'copying..'    && databricks fs cp --overwrite dist/$whl_file dbfs:/user/$USER_NAME/wheels
```

Update the library:
```
# options 1
echo 'installing..' && databricks libraries install --cluster-id 111-222-abcd \
                                                    --whl dbfs:/user/$USER_NAME/wheels/$whl_file
# option 2
echo 'uninstalling..' && databricks libraries uninstall --cluster-id 111-222-abcd \
                                                        --whl dbfs:/user/$USER_NAME/wheels/$whl_file
echo 'installing..'   && databricks libraries install --cluster-id 111-222-abcd \
                                                    --whl dbfs:/user/$USER_NAME/wheels/$whl_file
```

In both cases, the `databricks libraries install` command has no effect (irrespective of whether the version number of the new wheel file is greater than the currently installed version).

## Problems
1. `databricks libraries uninstall` doesn't uninstall unless the cluster is restarted.
2. `databricks libraries install` does nothing if package with same name is already installed.

## Expected behavior: 
1. `databricks libraries uninstall` uninstalls a package without requiring a cluster restart.
2. `databricks libraries install` behaves more like `pip install`
  * updates a package with same name if it is already installed and the new wheel file has a newer version of the package.
  * provides a way to forcefully reinstall same version of an already installed package. Like `pip --force-reinstall`

**Comment by pietern** [comment]
Hi @theKashyap,

The behavior you describe is expected, per the documentation. From the documentation for [library uninstall](https://docs.databricks.com/dev-tools/api/latest/libraries.html#uninstall):
> Set libraries to be uninstalled on a cluster. The libraries aren’t uninstalled until the cluster is restarted. Uninstalling libraries that are not installed on the cluster has no impact but is not an error.

These APIs are used for cluster wide installation of a library.

Are you sure you need your cluster's executors to use your library as well? E.g. is your custom code used in a Python UDF, or does it otherwise execute on the Spark executors? If not, you could consider installing your wheel file on the Spark driver alone, with `%pip install <wheel file>`. For more information on the latter, see https://docs.databricks.com/libraries/notebooks-python-libraries.html#manage-libraries-with-pip-commands.

I'm closing the issue because it's not something we can fix in the CLI.

**Comment by theKashyap** [comment]
ah, I guess I should've created it as a feature request.
@pietern
