### ISSUE TITLE
Running into path error when using workspace API on Windows Git Bash

### ISSUE THREAD

**Issue by erikschlegel** [databricks/databricks-cli#98]
I'm running into the error `Invalid_Parameter_Value` when using the workspace API on windows git bash. The workspace API works great in windows command prompt. 

![image](https://user-images.githubusercontent.com/7635865/37477751-76800fce-2846-11e8-8ec0-919fe80ffe51.png)

**Comment by westridge97330** [comment]
I can confirm this bug on PowerShell as well. Works fine in Linux where the /Users folder does not exist.  Seems to be a globbing issue but quoting the path does not help. Nor does turning off globbing with set -f

**Comment by jreynolds01** [comment]
I can also confirm this bug in git bash on Windows. It works ok in an Anaconda Prompt.

**Comment by charlesdarkwind** [comment]
Same here, any fix?

**Comment by sinamoeini** [comment]
The problem comes from MSys mangling the path to stop this behavior add `export MSYS_NO_PATHCONV=1`  to `~/.bash_profile` and reopen git bash

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.

**Comment by SzilvasiPeter** [comment]
If you are using Windows and Git then using a double slash `//` will solve the issue.

`databricks workspace ls //Users/<someone@example.com>`

As @sinamoeini pointed out, it is due to MSYS/MinGW translating the paths automatically. If you use a double slash then MSYS won't translate the path to DOS format.
